### ISSUE TITLE
need help to search product and customer

### ISSUE THREAD

**Issue by Dhamoderrick** [Dhamoderrick/invoice_application#2]

**Comment by imshines** [comment]
Reason for having that functionality. I think that is useless to have

**Comment by Dhamoderrick** [comment]
then how will you find customer/product among 50-60 entries

**Comment by imshines** [comment]
I'm working on it. Don't bother about that work on something else.

**Comment by Dhamoderrick** [comment]
https://stackoverflow.com/questions/10057480/creating-an-invoice-using-phpmysql

try this

**Comment by imshines** [comment]
close this issue almost fixed.
